//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GramSlam
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStat
    {
        public int Id { get; set; }
        public Nullable<int> MatcId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<bool> Win { get; set; }
        public Nullable<short> Aces { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
