//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GramSlam
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfo
    {
        public int Id { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<short> Weight { get; set; }
        public Nullable<short> Height { get; set; }
        public string Country { get; set; }
        public string BirthPlace { get; set; }
        public string Residence { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
